config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get("projects/:project_id/inventories" => "overviews#index")
get("projects/:project_id/inventories/overviews" => "overviews#index", :as => "overviews")

get("projects/:project_id/inventories/units" => "units#index", :as => "units")
get("projects/:project_id/inventories/units/new" => "units#new", :as => "units_new")
post("projects/:project_id/inventories/units" => "units#create")
get("projects/:project_id/inventories/units/:id" => "units#show", :as => "units_show")
get("projects/:project_id/inventories/units/:id/edit" => "units#edit", :as => "units_edit")
post("projects/:project_id/inventories/units/update" => "units#update")
delete("projects/:project_id/inventories/units/:id/destroy" => "units#destroy", :as => "units_destroy")

get("projects/:project_id/inventories/categories" => "categories#index", :as => "categories")
get("projects/:project_id/inventories/categories/new" => "categories#new", :as => "categories_new")
post("projects/:project_id/inventories/categories" => "categories#create")
get("projects/:project_id/inventories/categories/:id" => "categories#show", :as => "categories_show")
get("projects/:project_id/inventories/categories/:id/edit" => "categories#edit", :as => "categories_edit")
post("projects/:project_id/inventories/categories/update" => "categories#update")
delete("projects/:project_id/inventories/categories/:id/destroy" => "categories#destroy", :as => "categories_destroy")

get("projects/:project_id/inventories/rooms" => "rooms#index", :as => "rooms")
get("projects/:project_id/inventories/rooms/new" => "rooms#new", :as => "rooms_new")
post("projects/:project_id/inventories/rooms" => "rooms#create")
get("projects/:project_id/inventories/rooms/:id" => "rooms#show", :as => "rooms_show")
get("projects/:project_id/inventories/rooms/:id/edit" => "rooms#edit", :as => "rooms_edit")
post("projects/:project_id/inventories/rooms/update" => "rooms#update")
delete("projects/:project_id/inventories/rooms/:id/destroy" => "rooms#destroy", :as => "rooms_destroy")

get("projects/:project_id/inventories/amortnorms" => "amortnorms#index", :as => "amortnorms")
get("projects/:project_id/inventories/amortnorms/new" => "amortnorms#new", :as => "amortnorms_new")
post("projects/:project_id/inventories/amortnorms" => "amortnorms#create")
get("projects/:project_id/inventories/amortnorms/:id" => "amortnorms#show", :as => "amortnorms_show")
get("projects/:project_id/inventories/amortnorms/:id/edit" => "amortnorms#edit", :as => "amortnorms_edit")
post("projects/:project_id/inventories/amortnorms/update" => "amortnorms#update")
delete("projects/:project_id/inventories/amortnorms/:id/destroy" => "amortnorms#destroy", :as => "amortnorms_destroy")

get("projects/:project_id/inventories/histories" => "histories#index", :as => "histories")
get("projects/:project_id/inventories/histories/search" => "histories#index")
post("projects/:project_id/inventories/histories/search" => "histories#index", :as => "search_histories")

get("projects/:project_id/inventories/locations" => "locations#index", :as => "locations")
get("projects/:project_id/inventories/locations/new" => "locations#new", :as => "locations_new")
post("projects/:project_id/inventories/locations" => "locations#create")
get("projects/:project_id/inventories/locations/:id" => "locations#show", :as => "locations_show")
get("projects/:project_id/inventories/locations/:id/edit" => "locations#edit", :as => "locations_edit")
post("projects/:project_id/inventories/locations/update" => "locations#update")
delete("projects/:project_id/inventories/locations/:id/destroy" => "locations#destroy", :as => "locations_destroy")

get("projects/:project_id/inventories/index" => "inventories#index", :as => "inventories")
get("projects/:project_id/inventories/search" => "inventories#index")
get("projects/:project_id/inventories/new" => "inventories#new", :as => "inventories_new")
post("projects/:project_id/inventories/index" => "inventories#create")
get("projects/:project_id/inventories/:id" => "inventories#show", :as => "inventories_show")
get("projects/:project_id/inventories/:id/edit" => "inventories#edit", :as => "inventories_edit")
post("projects/:project_id/inventories/update" => "inventories#update")
delete("projects/:project_id/inventories/:id/destroy" => "inventories#destroy", :as => "inventories_destroy")
post("projects/:project_id/inventories/search" => "inventories#index", :as => "search_inventories")

app/models/amortnorm.rb
class Amortnorm < ActiveRecord::Base
  has_many(:units)
  validates(:name, :presence => true, :numericality => {:greater_than => -1, :less_than => 101})
end

app/controllers/amortnorms_controller.rb
class AmortnormsController < ApplicationController
  menu_item :overviews, :only => [:index, :show, :edit, :new, :update, :create]
  before_filter(:find_project, :authorize, :only => [:index, :show, :edit, :new, :update, :create])

  def index
    update_time_of_use
      @amortnorms = Amortnorm.all
  end

  def new
    update_time_of_use
    @amortnorm = Amortnorm.new
  end

  def create
    @amortnorm = Amortnorm.new(amortnorm_params)
    if(@amortnorm.save)
      redirect_to(:action => "index")
        flash[:notice] = l(:createMessage)
      else
        render("new")
      end
  end

  def show
    update_time_of_use
  end

  def update
    @amortnorm = Amortnorm.find(params[:id])
    if (@amortnorm.update_attributes(amortnorm_params))
      redirect_to(:action => "index")
      flash[:notice] = l(:updateMessage)
    else
      render("edit")
    end
  end

  def edit
    update_time_of_use
    @amortnorm = Amortnorm.find(params[:id])
  end

  def destroy
    @amortnorm = Amortnorm.find(params[:id])
      @amortnorm.destroy
      redirect_to(:action => "index")
  end

  private
    def amortnorm_params
    params.require(:amortnorm).permit(:name, :comment)
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end
  
  def update_time_of_use
    @inventories = Inventory.all
    @inventories.each do |inventory|
      inventory.update(:time_of_use => inventory.days)
    end
  end
end

app/helpers/amortnorms_helper.rb
module AmortnormsHelper
end

app/views/amortnorms/edit.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:amortnormHeader), amortnorms_path) + " " + l(:amortnormPathEdit) %></h2>
<% if @amortnorm.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @amortnorm.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(:amortnorm, :url => {:action => "update", :id => @amortnorm.id}) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:amortnormName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
				<em class = "info" style = "margin-left: 10px;"><%= l(:em2) %></em>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:amortnormComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:editSubmit)) %></p>
	<% end %>
<div>

app/views/amortnorms/index.html.erb
<div class = "contextual">
	<%= link_to(l(:addAmortnorm), amortnorms_new_path, :class => "icon icon-add") %>
</div>
<h2><%= l(:amortnormHeader) %></h2>
<div class = "tabs">
	<ul>
		<li><%= link_to(l(:goOverviews), overviews_path) %></li>
		<li><%= link_to(l(:goInventories), inventories_path) %></li>
		<li><%= link_to(l(:goUnits), units_path) %></li>
		<li><%= link_to(l(:goCategories), categories_path) %></li>
		<li><%= link_to(l(:goRooms), rooms_path) %></li>
		<li><%= link_to(l(:goLocations), locations_path) %></li>
		<li><%= link_to(l(:goAmortNorms), amortnorms_path, :onclick => "showTab('info', this.href); this.blur(); return false;", :id => "tab-info", :class => "selected") %></li>
		<li><%= link_to(l(:goHistories), histories_path) %></li>
	</ul>
</div>
<div style = "width: 50%">
	<div class = "autoscroll">
		<table class = "list">
			<thead>
				<tr>
					<th>ID</th>
					<th><%= l(:amortnormName) %></th>
					<th><%= l(:amortnormComment) %></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @amortnorms.each do |amortnorm| %>
					<tr class = "<%= cycle('user active odd', 'user active even') -%> user">
						<td><%= amortnorm.id %></td>
						<td><%= amortnorm.name + " %"%></td>
						<td><%= amortnorm.comment%></td>
						<td class = "buttons">
							<%= link_to(l(:edit), amortnorms_edit_path(:id => amortnorm.id), :class => "icon icon-edit") %>
							<%= link_to(l(:delete), amortnorms_destroy_path(:id => amortnorm.id), :method => :delete, :class => "icon icon-del", data: { confirm: l(:dataConfirm) }) %>
						</td>	
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>

app/views/amortnorms/new.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:amortnormHeader), amortnorms_path) + " " + l(:amortnormPathNew) %></h2>
<% if @amortnorm.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @amortnorm.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(@amortnorm) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:amortnormName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
				<em class = "info" style = "margin-left: 10px;"><%= l(:em2) %></em>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:amortnormComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:newSubmit)) %></p>
	<% end %>
<div>

app/views/amortnorms/show.html.erb
hjghjg