config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get("projects/:project_id/inventories" => "overviews#index")
get("projects/:project_id/inventories/overviews" => "overviews#index", :as => "overviews")

get("projects/:project_id/inventories/units" => "units#index", :as => "units")
get("projects/:project_id/inventories/units/new" => "units#new", :as => "units_new")
post("projects/:project_id/inventories/units" => "units#create")
get("projects/:project_id/inventories/units/:id" => "units#show", :as => "units_show")
get("projects/:project_id/inventories/units/:id/edit" => "units#edit", :as => "units_edit")
post("projects/:project_id/inventories/units/update" => "units#update")
delete("projects/:project_id/inventories/units/:id/destroy" => "units#destroy", :as => "units_destroy")

get("projects/:project_id/inventories/categories" => "categories#index", :as => "categories")
get("projects/:project_id/inventories/categories/new" => "categories#new", :as => "categories_new")
post("projects/:project_id/inventories/categories" => "categories#create")
get("projects/:project_id/inventories/categories/:id" => "categories#show", :as => "categories_show")
get("projects/:project_id/inventories/categories/:id/edit" => "categories#edit", :as => "categories_edit")
post("projects/:project_id/inventories/categories/update" => "categories#update")
delete("projects/:project_id/inventories/categories/:id/destroy" => "categories#destroy", :as => "categories_destroy")

get("projects/:project_id/inventories/rooms" => "rooms#index", :as => "rooms")
get("projects/:project_id/inventories/rooms/new" => "rooms#new", :as => "rooms_new")
post("projects/:project_id/inventories/rooms" => "rooms#create")
get("projects/:project_id/inventories/rooms/:id" => "rooms#show", :as => "rooms_show")
get("projects/:project_id/inventories/rooms/:id/edit" => "rooms#edit", :as => "rooms_edit")
post("projects/:project_id/inventories/rooms/update" => "rooms#update")
delete("projects/:project_id/inventories/rooms/:id/destroy" => "rooms#destroy", :as => "rooms_destroy")

get("projects/:project_id/inventories/amortnorms" => "amortnorms#index", :as => "amortnorms")
get("projects/:project_id/inventories/amortnorms/new" => "amortnorms#new", :as => "amortnorms_new")
post("projects/:project_id/inventories/amortnorms" => "amortnorms#create")
get("projects/:project_id/inventories/amortnorms/:id" => "amortnorms#show", :as => "amortnorms_show")
get("projects/:project_id/inventories/amortnorms/:id/edit" => "amortnorms#edit", :as => "amortnorms_edit")
post("projects/:project_id/inventories/amortnorms/update" => "amortnorms#update")
delete("projects/:project_id/inventories/amortnorms/:id/destroy" => "amortnorms#destroy", :as => "amortnorms_destroy")

get("projects/:project_id/inventories/histories" => "histories#index", :as => "histories")
get("projects/:project_id/inventories/histories/search" => "histories#index")
post("projects/:project_id/inventories/histories/search" => "histories#index", :as => "search_histories")

get("projects/:project_id/inventories/locations" => "locations#index", :as => "locations")
get("projects/:project_id/inventories/locations/new" => "locations#new", :as => "locations_new")
post("projects/:project_id/inventories/locations" => "locations#create")
get("projects/:project_id/inventories/locations/:id" => "locations#show", :as => "locations_show")
get("projects/:project_id/inventories/locations/:id/edit" => "locations#edit", :as => "locations_edit")
post("projects/:project_id/inventories/locations/update" => "locations#update")
delete("projects/:project_id/inventories/locations/:id/destroy" => "locations#destroy", :as => "locations_destroy")

get("projects/:project_id/inventories/index" => "inventories#index", :as => "inventories")
get("projects/:project_id/inventories/search" => "inventories#index")
get("projects/:project_id/inventories/new" => "inventories#new", :as => "inventories_new")
post("projects/:project_id/inventories/index" => "inventories#create")
get("projects/:project_id/inventories/:id" => "inventories#show", :as => "inventories_show")
get("projects/:project_id/inventories/:id/edit" => "inventories#edit", :as => "inventories_edit")
post("projects/:project_id/inventories/update" => "inventories#update")
delete("projects/:project_id/inventories/:id/destroy" => "inventories#destroy", :as => "inventories_destroy")
post("projects/:project_id/inventories/search" => "inventories#index", :as => "search_inventories")

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to(:location)
	has_many(:inventories, :dependent => :destroy)
	validates(:name, :presence => true, :uniqueness => true)
	validates(:prefix_id, :presence => true)
	validates(:location_id, :presence => true)
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  menu_item :overviews, :only => [:index, :show, :edit, :new, :update, :create]
  before_filter(:find_project, :authorize, :only => [:index, :show, :edit, :new, :update, :create])

  def index
    update_time_of_use
    @rooms = Room.all
  end

  def edit
    update_time_of_use
  	@room = Room.find(params[:id])
  end

  def update
	  @room = Room.find(params[:id])
	  if (@room.update_attributes(room_params))
      @locations = Location.all
      @locations.each do |location|
        if(location.id == @room.location.id)
          @room.update(:prefix_id => location.prefix + "-" + @room.prefix_id.to_s)
        end
      end
		  redirect_to(:action => "index")
      flash[:notice] = l(:updateMessage)
	  else
		  render("edit")
    end
  end

  def new
    update_time_of_use
  	@room = Room.new
  end

  def create
	  @room = Room.new(room_params)
	  if(@room.save)
      @locations = Location.all
      @locations.each do |location|
        if(location.id == @room.location.id)
          @room.update(:prefix_id => location.prefix + "-" + @room.prefix_id.to_s)
        end
      end
		  redirect_to(:action => "index")
      flash[:notice] = l(:createMessage)
	  else
		  render("new")
	  end
  end

  def show
    update_time_of_use
  	@room = Room.find(params[:id])
  end

  def destroy
	  @room = Room.find(params[:id])
	  @room.destroy
	  redirect_to(:action => "index")
  end

  private

  def room_params
  	params.require(:room).permit(:name, :prefix_id, :location_id, :comment)
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def update_time_of_use
    @inventories = Inventory.all
    @inventories.each do |inventory|
      inventory.update(:time_of_use => inventory.days)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:roomHeader), rooms_path) + " " + l(:roomPathEdit) %></h2>
<% if @room.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @room.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(:room, :url => {:action => "update", :id => @room.id}) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:roomName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:roomLocationId)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:location_id, Location.all, :id, :name, :prompt => "Select a Location") %>
			</p>
			<p>
				<%= f.label(l(:roomPrefixId)) %>
				<span class = "required">*</span>
				<% @locations = Location.all %>
				<% @locations.each do |location| %>
					<% if(location.id == @room.location.id) %>
						<%= f.text_field(:prefix_id, :value => @room.prefix_id[location.prefix.length + 1, @room.prefix_id.length]) %>
					<% end %>
				<% end %>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:roomComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:editSubmit)) %></p>
	<% end %>
<div>

app/views/rooms/index.html.erb
<div class = "contextual">
	<%= link_to(l(:addRoom), rooms_new_path, :class => "icon icon-add") %>
</div>
<h2><%= l(:roomHeader) %></h2>
<div class = "tabs">
	<ul>
		<li><%= link_to(l(:goOverviews), overviews_path) %></li>
		<li><%= link_to(l(:goInventories), inventories_path) %></li>
		<li><%= link_to(l(:goUnits), units_path) %></li>
		<li><%= link_to(l(:goCategories), categories_path) %></li>
		<li><%= link_to(l(:goRooms), rooms_path, :onclick => "showTab('info', this.href); this.blur(); return false;", :id => "tab-info", :class => "selected") %></li>
		<li><%= link_to(l(:goLocations), locations_path) %></li>
		<li><%= link_to(l(:goAmortNorms), amortnorms_path) %></li>
		<li><%= link_to(l(:goHistories), histories_path) %></li>
	</ul>
</div>
<div style = "width: 50%">
	<div class = "autoscroll">
		<table class = "list">
			<thead>
				<tr>
					<th>ID</th>
					<th><%= l(:roomName) %></th>
					<th><%= l(:roomLocationId) %></th>
					<th><%= l(:roomPrefixId) %></th>
					<th><%= l(:roomComment) %></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @rooms.each do |room| %>
					<tr class = "<%= cycle('user active odd', 'user active even') -%> user">
						<td><%= room.id %></td>
						<td><%= room.name %></td>
						<td><%= room.location.name %></td>
						<td><%= room.prefix_id %></td>
						<td><%= room.comment %></td>
						<td class = "buttons">
							<%= link_to(l(:edit), rooms_edit_path(:id => room.id), :class => "icon icon-edit") %>
							<%= link_to(l(:delete), rooms_destroy_path(:id => room.id), :method => :delete, :class => "icon icon-del", data: { confirm: l(:dataConfirm) }) %>
						</td>	
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>

app/views/rooms/new.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:roomHeader), rooms_path) + " " + l(:roomPathNew) %></h2>
<% if @room.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @room.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(@room) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:roomName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:roomLocationId)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:location_id, Location.all, :id, :name, :prompt => "Select a Location") %>
			</p>
			<p>
				<%= f.label(l(:roomPrefixId)) %>
				<span class = "required">*</span>
				<%= f.text_field(:prefix_id) %>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:roomComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:newSubmit)) %></p>
	<% end %>
<div>

app/views/rooms/show.html.erb
<div class = "permbajtja">
	<p><b>ID :</b><%= @room.id%></p>
	<p><b>Emri :</b><%= @room.name%></p>
	<p><b>Komenti :</b><%= @room.comment %></p>
	<p><%= button_to("Kthehu tek Index", rooms_path, :method => "get") %></p>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>