config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get("projects/:project_id/inventories" => "overviews#index")
get("projects/:project_id/inventories/overviews" => "overviews#index", :as => "overviews")

get("projects/:project_id/inventories/units" => "units#index", :as => "units")
get("projects/:project_id/inventories/units/new" => "units#new", :as => "units_new")
post("projects/:project_id/inventories/units" => "units#create")
get("projects/:project_id/inventories/units/:id" => "units#show", :as => "units_show")
get("projects/:project_id/inventories/units/:id/edit" => "units#edit", :as => "units_edit")
post("projects/:project_id/inventories/units/update" => "units#update")
delete("projects/:project_id/inventories/units/:id/destroy" => "units#destroy", :as => "units_destroy")

get("projects/:project_id/inventories/categories" => "categories#index", :as => "categories")
get("projects/:project_id/inventories/categories/new" => "categories#new", :as => "categories_new")
post("projects/:project_id/inventories/categories" => "categories#create")
get("projects/:project_id/inventories/categories/:id" => "categories#show", :as => "categories_show")
get("projects/:project_id/inventories/categories/:id/edit" => "categories#edit", :as => "categories_edit")
post("projects/:project_id/inventories/categories/update" => "categories#update")
delete("projects/:project_id/inventories/categories/:id/destroy" => "categories#destroy", :as => "categories_destroy")

get("projects/:project_id/inventories/rooms" => "rooms#index", :as => "rooms")
get("projects/:project_id/inventories/rooms/new" => "rooms#new", :as => "rooms_new")
post("projects/:project_id/inventories/rooms" => "rooms#create")
get("projects/:project_id/inventories/rooms/:id" => "rooms#show", :as => "rooms_show")
get("projects/:project_id/inventories/rooms/:id/edit" => "rooms#edit", :as => "rooms_edit")
post("projects/:project_id/inventories/rooms/update" => "rooms#update")
delete("projects/:project_id/inventories/rooms/:id/destroy" => "rooms#destroy", :as => "rooms_destroy")

get("projects/:project_id/inventories/amortnorms" => "amortnorms#index", :as => "amortnorms")
get("projects/:project_id/inventories/amortnorms/new" => "amortnorms#new", :as => "amortnorms_new")
post("projects/:project_id/inventories/amortnorms" => "amortnorms#create")
get("projects/:project_id/inventories/amortnorms/:id" => "amortnorms#show", :as => "amortnorms_show")
get("projects/:project_id/inventories/amortnorms/:id/edit" => "amortnorms#edit", :as => "amortnorms_edit")
post("projects/:project_id/inventories/amortnorms/update" => "amortnorms#update")
delete("projects/:project_id/inventories/amortnorms/:id/destroy" => "amortnorms#destroy", :as => "amortnorms_destroy")

get("projects/:project_id/inventories/histories" => "histories#index", :as => "histories")
get("projects/:project_id/inventories/histories/search" => "histories#index")
post("projects/:project_id/inventories/histories/search" => "histories#index", :as => "search_histories")

get("projects/:project_id/inventories/locations" => "locations#index", :as => "locations")
get("projects/:project_id/inventories/locations/new" => "locations#new", :as => "locations_new")
post("projects/:project_id/inventories/locations" => "locations#create")
get("projects/:project_id/inventories/locations/:id" => "locations#show", :as => "locations_show")
get("projects/:project_id/inventories/locations/:id/edit" => "locations#edit", :as => "locations_edit")
post("projects/:project_id/inventories/locations/update" => "locations#update")
delete("projects/:project_id/inventories/locations/:id/destroy" => "locations#destroy", :as => "locations_destroy")

get("projects/:project_id/inventories/index" => "inventories#index", :as => "inventories")
get("projects/:project_id/inventories/search" => "inventories#index")
get("projects/:project_id/inventories/new" => "inventories#new", :as => "inventories_new")
post("projects/:project_id/inventories/index" => "inventories#create")
get("projects/:project_id/inventories/:id" => "inventories#show", :as => "inventories_show")
get("projects/:project_id/inventories/:id/edit" => "inventories#edit", :as => "inventories_edit")
post("projects/:project_id/inventories/update" => "inventories#update")
delete("projects/:project_id/inventories/:id/destroy" => "inventories#destroy", :as => "inventories_destroy")
post("projects/:project_id/inventories/search" => "inventories#index", :as => "search_inventories")

app/models/unit.rb
class Unit < ActiveRecord::Base
	belongs_to :project
	
	 #acts_as_watchable	
	 acts_as_attachable :view_permission => :view_units
	 # 					:edit_permission => :view_attachments,
	 # 					:delete_permission => :view_attachments
                    
	 				#:view_permission => :view_attachments, 
                    
                    #:view_permission => :read_authorize
                    #:delete_permission => :view_attachments
	

	belongs_to(:category)
	belongs_to(:amortnorm)
	has_many :inventories, :dependent => :destroy
	validates(:category_id, :presence => true)
	validates(:normamort, :presence => true)
	validates :name, :presence => true, :uniqueness => true
	validates(:quantity, :presence => true, :numericality => {:greater_than => 0, :only_integer => true})
end

app/controllers/units_controller.rb
require 'securerandom'
require 'rqrcode_png'
class UnitsController < ApplicationController 
#require File.dirname(__FILE__) + '/../../../../app/helpers/attachments_helper'
#before_filter :find_attachments, :only => [:preview,:show,:download,:upload]

menu_item :overviews, :only => [:index, :show, :edit, :new, :update, :create]
before_filter(:find_project, :authorize, :only => [:index, :show, :edit, :new, :update, :create])


  helper :attachments
  include AttachmentsHelper      
  

  def index
    update_time_of_use
	  @units = Unit.all
    @categories = Category.all
  end
  
  def show
    if params[:version] && !User.current.allowed_to?(@project)
      deny_access
      return
    end
    
    update_time_of_use
 	  @unit = Unit.find(params[:id])
    @attachments = @unit.attachments.all
    @qr = RQRCode::QRCode.new(@unit.id.to_s+" "+@unit.name+" "+@unit.comment).to_img.resize(200, 200).to_data_url
  end
  
  def edit
    update_time_of_use
    @unit = Unit.find(params[:id])
  end
  
  def update
	  @unit = Unit.find(params[:id])
	  if (@unit.update_attributes(unit_params))
		  redirect_to(:action => "index")
      flash[:notice] = l(:updateMessage)
	  else
		  render(:controller => "units", :action => "edit")
	  end
  end
  
  def new
    update_time_of_use
    @unit = Unit.new
  end
  
  def create
    @unit = Unit.new(unit_params)
	  if(@unit.save)
      attachments = Attachment.attach_files(@unit, params[:attachments])
		redirect_to(:action => "index")
    flash[:notice] = l(:createMessage)
	  else
		  render("new")
	  end
  end

  
  
  def destroy
	  @unit = Unit.find(params[:id])
	  @unit.destroy
	  redirect_to(:action => "index")
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :normamort, :comment, :category_id, :quantity)
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end


  def update_time_of_use
    @inventories = Inventory.all
    @inventories.each do |inventory|
      inventory.update(:time_of_use => inventory.days)
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_links.html.erb
<div class="attachments">
<div class="contextual">
  <%#= link_to image_tag('edit.png'),
        container_attachments_edit_path(container),
        :title => l(:label_edit_attachments) if options[:editable] %>
</div>
<% for attachment in attachments %>
  <p><%= link_to_attachment attachment, :class => 'icon icon-attachment', :download => true -%>
  <% if attachment.is_text? %>
    <%= link_to image_tag('magnifier.png'),
                :controller => 'attachments', :action => 'show',
                :id => attachment, :filename => attachment.filename %>
  <% end %>
  <%= h(" - #{attachment.description}") unless attachment.description.blank? %>
  <span class="size">(<%= number_to_human_size attachment.filesize %>)</span>
  <% if( attachment.filename =~ /.(pdf|swf)$/i ) %>
    <%= link_to image_tag('preview.png', :plugin => :redmine_lightbox2), {
                  :controller => 'attachments', :action => 'download_inline',
                  :id => attachment, :filename => attachment.filename
                }, :class => $1.downcase + ' lightbox_preview', :rel => 'attachments',
                :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }",
                :data  => {:fancybox_type => 'iframe'} %>
  <% end -%>
  <% if( attachment.filename =~ /.(png|jpg|jpeg|gif)$/i ) %>
    <%= link_to image_tag('preview.png', :plugin => :redmine_lightbox2), {
                  :controller => 'attachments', :action => 'show',
                  :id => attachment, :filename => attachment.filename
                }, :class => $1.downcase + ' lightbox_preview', :rel => 'attachments',
                :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }" %>
  <% end -%>
  <% if options[:deletable] %>
    <%= link_to image_tag('delete.png'), attachment_path(attachment),
                                         :data => {:confirm => l(:text_are_you_sure)},
                                         :method => :delete,
                                         :class => 'delete',
                                         :title => l(:button_delete) %>
  <% end %>
  <% if options[:author] %>
    <span class="author"><%= h(attachment.author) %>, <%= format_time(attachment.created_on) %></span>
  <% end %>
  </p>
<% end %>

<% if defined?(thumbnails) && thumbnails %>
  <% images = attachments.select(&:thumbnailable?) %>
  <% if images.any? %>
  <div class="thumbnails images">
    <% images.each do |attachment| %>
      <div>
        <%=
          link_to image_tag(url_for(:controller => 'attachments', :action => 'thumbnail', :id => attachment)),
          {:controller => 'attachments', :action => 'show', :id => attachment, :filename => attachment.filename},
          :class => 'lightbox', :rel => 'thumbnails', :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }"
        %>
      </div>
    <% end %>
  </div>
  <% end %>
<% else %>
	<% images = attachments.select { |a| a.image? } %>
	<% unless images.empty? %>
	  <div class='images'>
	    <% images.each do |attachment| %>
	      <%= link_to image_tag(url_for({:controller => 'attachments', :action => 'show', :id => attachment, :filename => attachment.filename }), :width => '180'),
	      {:controller => 'attachments', :action => 'show', :id => attachment, :filename => attachment.filename }, :class => 'lightbox', :rel => 'thumbnails', :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }" %>
	    <% end -%>
	  </div>
	<% end -%>
<% end %>
</div>

app/views/units/edit.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:productHeader), units_path) + " " + l(:productPathEdit) %></h2>
<% if @unit.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @unit.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(:unit, :url => {:action => "update", :id => @unit.id}) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:productCategoryId)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => true)%>
			</p>
			<p>
				<%= f.label(l(:productNormamort)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:normamort, Amortnorm.all, :name, :name, :prompt => true)%>
			</p>
			<p>
				<%= f.label(l(:productName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:productQuantity)) %>
				<span class = "required">*</span>
				<%= f.text_field(:quantity) %>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:productComment)) %>
				<%= f.text_area(:comment) %>
			</p>
			
		</fieldset>
		<p><%= f.submit(l(:editSubmit)) %></p>
	<% end %>
<div>

app/views/units/index.html.erb
<div class = "contextual">
	<%= link_to(l(:addProduct), units_new_path, :class => "icon icon-add") %>
</div>
<h2><%= l(:productHeader) %></h2>
<div class = "tabs">
	<ul>
		<li><%= link_to(l(:goOverviews), overviews_path) %></li>
		<li><%= link_to(l(:goInventories), inventories_path) %></li>
		<li><%= link_to(l(:goUnits), units_path, :onclick => "showTab('info', this.href); this.blur(); return false;", :id => "tab-info", :class => "selected") %></li>
		<li><%= link_to(l(:goCategories), categories_path) %></li>
		<li><%= link_to(l(:goRooms), rooms_path) %></li>
		<li><%= link_to(l(:goLocations), locations_path) %></li>
		<li><%= link_to(l(:goAmortNorms), amortnorms_path) %></li>
		<li><%= link_to(l(:goHistories), histories_path) %></li>
	</ul>
</div>
<div class = "autoscroll">
	<table class = "list">
		<thead>
			<tr>
				<th>ID</th>
				<th><%= l(:productCategoryId) %></th>
				<th><%= l(:productName) %></th>
				<th><%= l(:productNormamort) %></th>
				<th><%= l(:productQuantity) %></th>
				<th><%= l(:productComment) %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @units.each do |unit| %>
				<tr class = "<%= cycle('user active odd', 'user active even') -%> user">
					<td><%= unit.id %></td>
					<% @categories.each do |category| %>
						<% if(unit.category_id == category.id) %>
							<td><%= category.name %></td>
						<% end %>
					<% end %>
					<td><%= unit.name %></td>
					<td><%= unit.normamort.to_s + " %" %></td>
					<td><%= unit.quantity %></td>
					<td><%= unit.comment%></td>
					<%#= render 'links' %>
					<td class = "buttons">
					<%= link_to((:show), units_show_path(:id => unit.id))%>
						<%= link_to(l(:edit), units_edit_path(:id => unit.id), :class => "icon icon-edit") %>
						<%= link_to(l(:delete), units_destroy_path(:id => unit.id), :method => :delete, :class => "icon icon-del", data: { confirm: l(:dataConfirm) }) %>
					</td>	
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>

app/views/units/new.html.erb
<% require 'securerandom' %>
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:productHeader), units_path) + " " + l(:productPathNew) %></h2>
<% if @unit.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @unit.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(@unit) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:productCategoryId)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => true)%>
			</p>
			<p>
				<%= f.label(l(:productNormamort)) %>
				<span class = "required">*</span>
				<%= f.collection_select(:normamort, Amortnorm.all, :name, :name, :prompt => true)%>
			</p>
			<p>
				<%= f.label(l(:productName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:productQuantity)) %>
				<span class = "required">*</span>
				<%= f.text_field(:quantity) %>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:productComment)) %>
				<%= f.text_area(:comment) %>
			</p>
			<p>
				<%= render :partial => 'attachments/form' %>
				</p>
		</fieldset>
		<p><%= f.submit(l(:newSubmit)) %></p>
	<% end %>
<div>

app/views/units/show.html.erb
<%= image_tag @qr %>

<%#= link_to_attachments @unit, :thumbnails => true %>

<%#= link_to_attachments @page %>

	<%= link_to_attachments(@unit)  %>
	
<%#=  render "attachments/links" %>