config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get("projects/:project_id/inventories" => "overviews#index")
get("projects/:project_id/inventories/overviews" => "overviews#index", :as => "overviews")

get("projects/:project_id/inventories/units" => "units#index", :as => "units")
get("projects/:project_id/inventories/units/new" => "units#new", :as => "units_new")
post("projects/:project_id/inventories/units" => "units#create")
get("projects/:project_id/inventories/units/:id" => "units#show", :as => "units_show")
get("projects/:project_id/inventories/units/:id/edit" => "units#edit", :as => "units_edit")
post("projects/:project_id/inventories/units/update" => "units#update")
delete("projects/:project_id/inventories/units/:id/destroy" => "units#destroy", :as => "units_destroy")

get("projects/:project_id/inventories/categories" => "categories#index", :as => "categories")
get("projects/:project_id/inventories/categories/new" => "categories#new", :as => "categories_new")
post("projects/:project_id/inventories/categories" => "categories#create")
get("projects/:project_id/inventories/categories/:id" => "categories#show", :as => "categories_show")
get("projects/:project_id/inventories/categories/:id/edit" => "categories#edit", :as => "categories_edit")
post("projects/:project_id/inventories/categories/update" => "categories#update")
delete("projects/:project_id/inventories/categories/:id/destroy" => "categories#destroy", :as => "categories_destroy")

get("projects/:project_id/inventories/rooms" => "rooms#index", :as => "rooms")
get("projects/:project_id/inventories/rooms/new" => "rooms#new", :as => "rooms_new")
post("projects/:project_id/inventories/rooms" => "rooms#create")
get("projects/:project_id/inventories/rooms/:id" => "rooms#show", :as => "rooms_show")
get("projects/:project_id/inventories/rooms/:id/edit" => "rooms#edit", :as => "rooms_edit")
post("projects/:project_id/inventories/rooms/update" => "rooms#update")
delete("projects/:project_id/inventories/rooms/:id/destroy" => "rooms#destroy", :as => "rooms_destroy")

get("projects/:project_id/inventories/amortnorms" => "amortnorms#index", :as => "amortnorms")
get("projects/:project_id/inventories/amortnorms/new" => "amortnorms#new", :as => "amortnorms_new")
post("projects/:project_id/inventories/amortnorms" => "amortnorms#create")
get("projects/:project_id/inventories/amortnorms/:id" => "amortnorms#show", :as => "amortnorms_show")
get("projects/:project_id/inventories/amortnorms/:id/edit" => "amortnorms#edit", :as => "amortnorms_edit")
post("projects/:project_id/inventories/amortnorms/update" => "amortnorms#update")
delete("projects/:project_id/inventories/amortnorms/:id/destroy" => "amortnorms#destroy", :as => "amortnorms_destroy")

get("projects/:project_id/inventories/histories" => "histories#index", :as => "histories")
get("projects/:project_id/inventories/histories/search" => "histories#index")
post("projects/:project_id/inventories/histories/search" => "histories#index", :as => "search_histories")

get("projects/:project_id/inventories/locations" => "locations#index", :as => "locations")
get("projects/:project_id/inventories/locations/new" => "locations#new", :as => "locations_new")
post("projects/:project_id/inventories/locations" => "locations#create")
get("projects/:project_id/inventories/locations/:id" => "locations#show", :as => "locations_show")
get("projects/:project_id/inventories/locations/:id/edit" => "locations#edit", :as => "locations_edit")
post("projects/:project_id/inventories/locations/update" => "locations#update")
delete("projects/:project_id/inventories/locations/:id/destroy" => "locations#destroy", :as => "locations_destroy")

get("projects/:project_id/inventories/index" => "inventories#index", :as => "inventories")
get("projects/:project_id/inventories/search" => "inventories#index")
get("projects/:project_id/inventories/new" => "inventories#new", :as => "inventories_new")
post("projects/:project_id/inventories/index" => "inventories#create")
get("projects/:project_id/inventories/:id" => "inventories#show", :as => "inventories_show")
get("projects/:project_id/inventories/:id/edit" => "inventories#edit", :as => "inventories_edit")
post("projects/:project_id/inventories/update" => "inventories#update")
delete("projects/:project_id/inventories/:id/destroy" => "inventories#destroy", :as => "inventories_destroy")
post("projects/:project_id/inventories/search" => "inventories#index", :as => "search_inventories")

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :units, :dependent => :destroy
	validates :name, :presence => true
	validates :prefixid, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/}

def err

end

	def uniquecode
          raw_string = SecureRandom.random_number( 2**80 ).to_s( 20 ).reverse
          long_code = raw_string.tr( '0123456789abcdefghij', '234679QWERTYUPADFGHX' )
          self.prefixid+'-'+long_code[4..7]+'-'+long_code[8..11]
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  menu_item :overviews, :only => [:index, :show, :edit, :new, :update, :create]
  before_filter(:find_project, :authorize, :only => [:index, :show, :edit, :new, :update, :create])

  def index
    update_time_of_use
  	@categories = Category.all
  end

  def show
    update_time_of_use
  	@category = Category.find(params[:id])
  end

  def edit
    update_time_of_use
  	@category = Category.find(params[:id])
  end

  def new
    update_time_of_use
  	@category = Category.new
  end

  def create
	  @category = Category.new(category_params)
	  if(@category.save)
		  redirect_to(:action => "index")
      flash[:notice] = l(:createMessage)
	  else
		  render("new")
    end
  end

  def update
	  @category = Category.find(params[:id])
    if (@category.update_attributes(category_params))
      redirect_to(:action => "index")
      flash[:notice] = l(:updateMessage)
    else 
      render("edit") 
	  end 
  end

  def destroy
	  @category = Category.find(params[:id])
	  @category.destroy
	  redirect_to(:action => "index")
  end

 private

  def category_params
    params.require(:category).permit(:name, :comment, :prefixid)
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def update_time_of_use
    @inventories = Inventory.all
    @inventories.each do |inventory|
      inventory.update(:time_of_use => inventory.days)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:categoryHeader), categories_path) + " " + l(:categoryPathEdit) %></h2>
<% if @category.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(:category, :url => {:action => "update", :id => @category.id}) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:categoryName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:categoryPrefixid)) %>
				<span class = "required">*</span>
				<%= f.text_field(:prefixid) %>
				<em class = "info" style = "margin-left: 10px;"><%= l(:em1) %></em>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:categoryComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:editSubmit)) %></p>
	<% end %>
<div>

app/views/categories/index.html.erb
<div class = "contextual">
	<%= link_to(l(:addCategory), categories_new_path, :class => "icon icon-add") %>
</div>
<h2><%= l(:categoryHeader) %></h2>
<div class = "tabs">
	<ul>
		<li><%= link_to(l(:goOverviews), overviews_path) %></li>
		<li><%= link_to(l(:goInventories), inventories_path) %></li>
		<li><%= link_to(l(:goUnits), units_path) %></li>
		<li><%= link_to(l(:goCategories), categories_path, :onclick => "showTab('info', this.href); this.blur(); return false;", :id => "tab-info", :class => "selected") %></li>
		<li><%= link_to(l(:goRooms), rooms_path) %></li>
		<li><%= link_to(l(:goLocations), locations_path) %></li>
		<li><%= link_to(l(:goAmortNorms), amortnorms_path) %></li>
		<li><%= link_to(l(:goHistories), histories_path) %></li>
	</ul>
</div>
<div style = "width: 50%">
	<div class = "autoscroll">
		<table class = "list">
			<thead>
				<tr>
					<th>ID</th>
					<th><%= l(:categoryName) %></th>
					<th><%= l(:categoryComment) %></th>
					<th><%= l(:categoryPrefixid) %></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @categories.each do |category| %>
					<tr class = "<%= cycle('user active odd', 'user active even') -%> user">
						<td><%= category.id %></td>
						<td><%= category.name %></td>
						<td><%= category.comment %></td>
						<td><%= category.prefixid %></td>
						<td class = "buttons">
							<%= link_to(l(:edit), categories_edit_path(:id => category.id), :class => "icon icon-edit") %>
							<%= link_to(l(:delete), categories_destroy_path(:id => category.id), :method => :delete, :class => "icon icon-del", data: { confirm: l(:dataConfirm) }) %>
						</td>	
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>

app/views/categories/new.html.erb
<style type="text/css">
	.splitcontentleft fieldset input {
		width: 90%;
	}
	.splitcontentleft fieldset select {
		width: 90%;
	}
	.splitcontentleft textarea {
		width: 90%;
		height: 70px;
	}
</style>
<h2><%= link_to(l(:categoryHeader), categories_path) + " " + l(:categoryPathNew) %></h2>
<% if @category.errors.any? %>
	<div id = "errorExplanation">
		<ul>
			<% @category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class = "splitcontentleft">
	<%= form_for(@category) do |f| %>
		<fieldset class = "box tabular">
			<legend><%= l(:legend1) %></legend>
			<p>
				<%= f.label(l(:categoryName)) %>
				<span class = "required">*</span>
				<%= f.text_field(:name) %>
			</p>
			<p>
				<%= f.label(l(:categoryPrefixid)) %>
				<span class = "required">*</span>
				<%= f.text_field(:prefixid) %>
				<em class = "info" style = "margin-left: 10px;"><%= l(:em1) %></em>
			</p>
		</fieldset>
		<fieldset class = "box tabular">
			<legend><%= l(:legend2) %></legend>
			<p>
				<%= f.label(l(:categoryComment)) %>
				<%= f.text_area(:comment) %>
			</p>
		</fieldset>
		<p><%= f.submit(l(:newSubmit)) %></p>
	<% end %>
<div>

app/views/categories/show.html.erb
<div class= "permbajtja">
	<h1>Shfaqja e te dhenave</h1>
	<p><b>Kategoria ID :</b> <%= @category.id %></p>
	<p><b>Emri i Kategorise :</b> <%= @category.name %></p>
	<p><b>Komenti :</b><%= @category.comment %></p>
	<p><%= button_to("Kthehu tek Index", categories_path, :method => "get") %></p>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'style', :plugin => 'regjistrimi_inventarit' %>
<% end %>